import type { Capability, RiskLevel, UnderstandResult } from "../core/types.js";

interface Card {
  id: string;
  title: string;
  subtitle: string;
  risk: RiskLevel | "info";
  x: number;
  y: number;
  width: number;
  height: number;
}

const width = 1200;
const height = 850;
const centerX = width / 2;

export function renderVisualChainsSvg(result: UnderstandResult): string {
  const riskCards = result.riskChains.slice(0, 5).map((chain, index): Card => ({
    id: chain.id,
    title: chain.name,
    subtitle: `${chain.capabilities.join(" + ")} · ${chain.risk.toUpperCase()}`,
    risk: chain.risk,
    x: 70,
    y: 210 + index * 105,
    width: 470,
    height: 80
  }));

  const guardrailCards = result.controlGaps.slice(0, 5).map((gap, index): Card => ({
    id: gap.id,
    title: humanize(gap.control),
    subtitle: `${gap.risk.toUpperCase()} · ${gap.message}`,
    risk: gap.risk,
    x: 660,
    y: 210 + index * 105,
    width: 470,
    height: 80
  }));

  const capabilityLabels = result.capabilities
    .slice()
    .sort((a, b) => riskRank(b.risk) - riskRank(a.risk) || b.count - a.count || a.capability.localeCompare(b.capability))
    .slice(0, 8)
    .map((capability) => `${humanize(capability.capability)} (${capability.count})`);

  const surfaceLabels = result.inventory.surfaces
    .slice(0, 8)
    .map((surface) => `${surface.label}${surface.capabilities.length ? ` · ${surface.capabilities.length} cap` : ""}`);

  const summary = result.summary;
  const title = "WHAT THE AGENT CAN DO";
  const riskTotal = result.riskChains.length;
  const controlGapTotal = result.controlGaps.length;

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="title desc">
  <title id="title">${escapeXml(title)}</title>
  <desc id="desc">Visual summary of agent capabilities, risky chains, and missing guardrails generated by WhatTheAgent.</desc>
  <defs>
    <filter id="paperShadow" x="-10%" y="-10%" width="120%" height="120%">
      <feDropShadow dx="0" dy="3" stdDeviation="3" flood-color="#000000" flood-opacity="0.14"/>
    </filter>
    <marker id="arrow" markerWidth="12" markerHeight="12" refX="10" refY="6" orient="auto" markerUnits="strokeWidth">
      <path d="M2,2 L10,6 L2,10 Z" fill="#222"/>
    </marker>
  </defs>

  <rect width="100%" height="100%" fill="#ffffff"/>
  <rect x="28" y="28" width="1144" height="794" rx="24" fill="#fffdf8" stroke="#222" stroke-width="2" filter="url(#paperShadow)"/>

  ${titleBox(title)}
  ${summaryStats(summary.capabilityCount, riskTotal, controlGapTotal)}

  <text x="90" y="175" class="section-title">RISK CHAINS</text>
  <text x="680" y="175" class="section-title">MISSING GUARDRAILS</text>
  ${riskCards.length === 0 ? emptyCard(70, 230, "NO ACTIVE RISK CHAINS", "Only ordinary inventory or expected behavior detected.") : riskCards.map(renderCard).join("\n")}
  ${guardrailCards.length === 0 ? emptyCard(660, 230, "NO CONTROL GAPS", "No missing guardrails were identified from this scan.") : guardrailCards.map(renderCard).join("\n")}
  ${connectionArrows(riskCards, guardrailCards)}

  ${listPanel(70, 720, 470, "TOP CAPABILITIES", capabilityLabels.length ? capabilityLabels : ["No capabilities detected"])}
  ${listPanel(660, 720, 470, "DETECTED SURFACES", surfaceLabels.length ? surfaceLabels : ["No agent surfaces detected"])}

  <g transform="translate(565 525)">
    <circle cx="35" cy="35" r="34" fill="#d7f0ee" stroke="#222" stroke-width="2"/>
    <path d="M20 38 L31 49 L52 22" fill="none" stroke="#222" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>
    <text x="35" y="92" text-anchor="middle" class="small-title">VERIFY</text>
  </g>

  <text x="600" y="805" text-anchor="middle" class="footer">LOCAL STATIC REPORT · SECRETS REDACTED · REVIEW .wta/ BEFORE SHARING</text>

  <style>
    .title { font-family: Arial, Helvetica, sans-serif; font-size: 34px; font-weight: 900; letter-spacing: 1px; fill: #111; }
    .section-title { font-family: Arial, Helvetica, sans-serif; font-size: 22px; font-weight: 900; letter-spacing: 1px; fill: #111; }
    .card-title { font-family: Arial, Helvetica, sans-serif; font-size: 17px; font-weight: 900; fill: #111; }
    .card-subtitle { font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-weight: 700; fill: #333; }
    .small-title { font-family: Arial, Helvetica, sans-serif; font-size: 13px; font-weight: 900; fill: #111; }
    .stat-number { font-family: Arial, Helvetica, sans-serif; font-size: 24px; font-weight: 900; fill: #111; }
    .stat-label { font-family: Arial, Helvetica, sans-serif; font-size: 11px; font-weight: 800; fill: #333; }
    .list-text { font-family: Arial, Helvetica, sans-serif; font-size: 13px; font-weight: 700; fill: #111; }
    .footer { font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-weight: 800; fill: #555; letter-spacing: .5px; }
  </style>
</svg>`;
}

function titleBox(title: string): string {
  return `<g>
    <rect x="365" y="62" width="470" height="72" rx="8" fill="#f6d49b" stroke="#222" stroke-width="3"/>
    <path d="M382 134 L850 134 L830 153 L365 153 Z" fill="#e9a45f" stroke="#222" stroke-width="3"/>
    <path d="M835 79 L858 98 L858 134 L835 134 Z" fill="#c7645e" stroke="#222" stroke-width="3"/>
    <text x="600" y="108" text-anchor="middle" class="title">${escapeXml(title)}</text>
  </g>`;
}

function summaryStats(capabilities: number, chains: number, gaps: number): string {
  const stats = [
    { label: "CAPABILITIES", value: capabilities, x: 110, fill: "#d7f0ee" },
    { label: "RISK CHAINS", value: chains, x: 235, fill: "#f6d49b" },
    { label: "GUARDRAILS", value: gaps, x: 960, fill: "#efb3ad" }
  ];
  return `<g>${stats.map((stat) => `<g transform="translate(${stat.x} 72)">
    <rect x="0" y="0" width="105" height="66" rx="14" fill="${stat.fill}" stroke="#222" stroke-width="2"/>
    <text x="52" y="30" text-anchor="middle" class="stat-number">${stat.value}</text>
    <text x="52" y="50" text-anchor="middle" class="stat-label">${stat.label}</text>
  </g>`).join("\n")}</g>`;
}

function renderCard(card: Card): string {
  const accent = colorForRisk(card.risk);
  return `<g>
    <rect x="${card.x}" y="${card.y}" width="${card.width}" height="${card.height}" rx="18" fill="#ffffff" stroke="#222" stroke-width="2"/>
    <rect x="${card.x}" y="${card.y}" width="16" height="${card.height}" rx="8" fill="${accent}" stroke="#222" stroke-width="2"/>
    <circle cx="${card.x + 39}" cy="${card.y + 40}" r="16" fill="${accent}" stroke="#222" stroke-width="2"/>
    <text x="${card.x + 66}" y="${card.y + 32}" class="card-title">${escapeXml(truncate(card.title, 42))}</text>
    <text x="${card.x + 66}" y="${card.y + 55}" class="card-subtitle">${escapeXml(truncate(card.subtitle, 72))}</text>
  </g>`;
}

function emptyCard(x: number, y: number, title: string, subtitle: string): string {
  return renderCard({ id: title, title, subtitle, risk: "info", x, y, width: 470, height: 80 });
}

function connectionArrows(left: Card[], right: Card[]): string {
  const count = Math.min(left.length, right.length, 5);
  const arrows: string[] = [];
  for (let index = 0; index < count; index += 1) {
    const source = left[index];
    const target = right[index];
    if (!source || !target) continue;
    const y = source.y + source.height / 2;
    arrows.push(`<path d="M${source.x + source.width + 10} ${y} C ${centerX - 40} ${y}, ${centerX + 40} ${target.y + target.height / 2}, ${target.x - 10} ${target.y + target.height / 2}" fill="none" stroke="#222" stroke-width="2" stroke-dasharray="8 7" marker-end="url(#arrow)"/>`);
  }
  return arrows.join("\n");
}

function listPanel(x: number, y: number, panelWidth: number, title: string, items: string[]): string {
  const renderedItems = items.slice(0, 6).map((item, index) => `<text x="${x + 28}" y="${y + 62 + index * 22}" class="list-text">• ${escapeXml(truncate(item, 54))}</text>`).join("\n");
  return `<g>
    <rect x="${x}" y="${y}" width="${panelWidth}" height="120" rx="18" fill="#f8faf9" stroke="#222" stroke-width="2"/>
    <text x="${x + 24}" y="${y + 32}" class="small-title">${escapeXml(title)}</text>
    ${renderedItems}
  </g>`;
}

function colorForRisk(risk: RiskLevel | "info"): string {
  switch (risk) {
    case "critical":
    case "high":
      return "#c7645e";
    case "medium":
      return "#e9a45f";
    case "low":
    case "info":
    default:
      return "#68b8b0";
  }
}

function riskRank(risk: RiskLevel): number {
  switch (risk) {
    case "critical":
      return 4;
    case "high":
      return 3;
    case "medium":
      return 2;
    case "low":
      return 1;
  }
}

function humanize(value: Capability | string): string {
  return value.replace(/_/g, " ").toUpperCase();
}

function truncate(value: string, maxLength: number): string {
  return value.length <= maxLength ? value : `${value.slice(0, maxLength - 1)}…`;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}
